_include "include/sns/autoscale.rb"
_include "include/cloudwatch/autoscale.rb"
_include "include/ec2/autoscale/as-group.rb"
_include "include/ec2/autoscale/as-setting.rb"
_include "include/ec2/autoscale/as-policy.rb"
