AMIMOTOConfig(
  {
    "mobile-detect"=>{
      "enabled"=>"true",
      "disabled"=>"false"
    },
    "wp-multisite"=>{
      "enabled"=>"true",
      "disabled"=>"false"
    },
    "php-myadmin"=>{
      "enabled"=>"true",
      "disabled"=>"false"
    }
  }
)
